### PR TITLE
Dom polyfill docs & tests

### PR DESCRIPTION
**Pull request by skidding**

### CODE REVIEW

**Comment by skidding** [comment]
@bogdan-stefan-hs please review

**Comment by skidding** [comment]
Coverage is [fine](https://coveralls.io/builds/7669043/source?filename=packages%2Freact-dom-polyfill%2Fsrc%2Findex.js#L9), that try catch is there for webpack's static analysis.

**Comment by flavius-tirnacop-hs** [comment]
Looking good 👍

**Comment by bogdanstefan** [comment]
Looks great! 👍 
Did you get the chance to test it with another bundler besides webpack to see how it acts when `react-dom` is missing?

**Comment by skidding** [comment]
> Did you get the chance to test it with another bundler besides webpack to see how it behaves when react-dom is missing?

No. But good idea. I'll try a Browserify setup before we submit any external PR. 👍

**Pull request merged**
